---
- yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: "Install nginx"
  yum:
    name: nginx
    state: present
- name: "Copy nginx conf file to server"
  copy:
    src: templates/nginx.conf
    dest: /etc/nginx/conf.d/nginx.conf
- name: "Install certbot"
  yum:
    name: python2-certbot-nginx
    state: present
- name: "Restart nginx"
  service:
    name: nginx
    state: restarted
- name: "Configure certbot"
  shell: 'certbot -i nginx -n -d "iloveansible2.tk" --nginx -m "yodeusz@gmail.com" --agree-tos --redirect'